
variables:
  buildConfiguration: 'Release'

jobs:
- job: BuildAndPuplish
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - script: dotnet build ./src/PSO/PSO.fsproj --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY
    displayName: 'build'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: CI-Binaries
