pr:
  - master

jobs:

- job: Windows
  pool:
    vmImage: windows-2019
  steps:
  - powershell: ./build.ps1 -Target Build

- job: Delivery
  dependsOn:
  - Windows
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  pool:
    vmImage: windows-2019
  steps:
    - powershell:  ./build.ps1 -Target Publish-Nuget
